# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slack_web_python_sdk import schemas  # noqa: F401


class AdminconversationsGetTeamsListResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Schema for successful response of admin.conversations.getTeams
    """


    class MetaOapg:
        required = {
            "team_ids",
            "ok",
        }
        
        class properties:
        
            @staticmethod
            def ok() -> typing.Type['DefsOkTrue']:
                return DefsOkTrue
            
            
            class team_ids(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['DefsTeam']:
                        return DefsTeam
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['DefsTeam'], typing.List['DefsTeam']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'team_ids':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'DefsTeam':
                    return super().__getitem__(i)
        
            @staticmethod
            def response_metadata() -> typing.Type['AdminconversationsGetTeamsListResponseResponseMetadata']:
                return AdminconversationsGetTeamsListResponseResponseMetadata
            __annotations__ = {
                "ok": ok,
                "team_ids": team_ids,
                "response_metadata": response_metadata,
            }
    
    team_ids: MetaOapg.properties.team_ids
    ok: 'DefsOkTrue'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ok"]) -> 'DefsOkTrue': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["team_ids"]) -> MetaOapg.properties.team_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["response_metadata"]) -> 'AdminconversationsGetTeamsListResponseResponseMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["ok", "team_ids", "response_metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ok"]) -> 'DefsOkTrue': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["team_ids"]) -> MetaOapg.properties.team_ids: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["response_metadata"]) -> typing.Union['AdminconversationsGetTeamsListResponseResponseMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["ok", "team_ids", "response_metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        team_ids: typing.Union[MetaOapg.properties.team_ids, list, tuple, ],
        ok: 'DefsOkTrue',
        response_metadata: typing.Union['AdminconversationsGetTeamsListResponseResponseMetadata', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AdminconversationsGetTeamsListResponse':
        return super().__new__(
            cls,
            *args,
            team_ids=team_ids,
            ok=ok,
            response_metadata=response_metadata,
            _configuration=_configuration,
            **kwargs,
        )

from slack_web_python_sdk.model.adminconversations_get_teams_list_response_response_metadata import AdminconversationsGetTeamsListResponseResponseMetadata
from slack_web_python_sdk.model.defs_ok_true import DefsOkTrue
from slack_web_python_sdk.model.defs_team import DefsTeam
