# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slack_web_python_sdk import schemas  # noqa: F401


class AdminusergroupsAssociateDefaultWorkspacesRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "team_ids",
            "usergroup_id",
        }
        
        class properties:
            team_ids = schemas.StrSchema
            usergroup_id = schemas.StrSchema
            auto_provision = schemas.BoolSchema
            __annotations__ = {
                "team_ids": team_ids,
                "usergroup_id": usergroup_id,
                "auto_provision": auto_provision,
            }
    
    team_ids: MetaOapg.properties.team_ids
    usergroup_id: MetaOapg.properties.usergroup_id
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["team_ids"]) -> MetaOapg.properties.team_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usergroup_id"]) -> MetaOapg.properties.usergroup_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["auto_provision"]) -> MetaOapg.properties.auto_provision: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["team_ids", "usergroup_id", "auto_provision", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["team_ids"]) -> MetaOapg.properties.team_ids: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usergroup_id"]) -> MetaOapg.properties.usergroup_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["auto_provision"]) -> typing.Union[MetaOapg.properties.auto_provision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["team_ids", "usergroup_id", "auto_provision", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        team_ids: typing.Union[MetaOapg.properties.team_ids, str, ],
        usergroup_id: typing.Union[MetaOapg.properties.usergroup_id, str, ],
        auto_provision: typing.Union[MetaOapg.properties.auto_provision, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AdminusergroupsAssociateDefaultWorkspacesRequest':
        return super().__new__(
            cls,
            *args,
            team_ids=team_ids,
            usergroup_id=usergroup_id,
            auto_provision=auto_provision,
            _configuration=_configuration,
            **kwargs,
        )
