# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slack_web_python_sdk import schemas  # noqa: F401


class FilesInfoResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Schema for successful response from files.info method
    """


    class MetaOapg:
        required = {
            "comments",
            "file",
            "ok",
        }
        
        class properties:
        
            @staticmethod
            def comments() -> typing.Type['ObjsComments']:
                return ObjsComments
        
            @staticmethod
            def file() -> typing.Type['ObjsFile']:
                return ObjsFile
        
            @staticmethod
            def ok() -> typing.Type['DefsOkTrue']:
                return DefsOkTrue
            content_html = schemas.AnyTypeSchema
        
            @staticmethod
            def editor() -> typing.Type['DefsUserId']:
                return DefsUserId
        
            @staticmethod
            def paging() -> typing.Type['ObjsPaging']:
                return ObjsPaging
        
            @staticmethod
            def response_metadata() -> typing.Type['ObjsResponseMetadata']:
                return ObjsResponseMetadata
            __annotations__ = {
                "comments": comments,
                "file": file,
                "ok": ok,
                "content_html": content_html,
                "editor": editor,
                "paging": paging,
                "response_metadata": response_metadata,
            }
    
    comments: 'ObjsComments'
    file: 'ObjsFile'
    ok: 'DefsOkTrue'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comments"]) -> 'ObjsComments': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file"]) -> 'ObjsFile': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ok"]) -> 'DefsOkTrue': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["content_html"]) -> MetaOapg.properties.content_html: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["editor"]) -> 'DefsUserId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["paging"]) -> 'ObjsPaging': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["response_metadata"]) -> 'ObjsResponseMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["comments", "file", "ok", "content_html", "editor", "paging", "response_metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comments"]) -> 'ObjsComments': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file"]) -> 'ObjsFile': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ok"]) -> 'DefsOkTrue': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["content_html"]) -> typing.Union[MetaOapg.properties.content_html, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["editor"]) -> typing.Union['DefsUserId', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["paging"]) -> typing.Union['ObjsPaging', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["response_metadata"]) -> typing.Union['ObjsResponseMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["comments", "file", "ok", "content_html", "editor", "paging", "response_metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        comments: 'ObjsComments',
        file: 'ObjsFile',
        ok: 'DefsOkTrue',
        content_html: typing.Union[MetaOapg.properties.content_html, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        editor: typing.Union['DefsUserId', schemas.Unset] = schemas.unset,
        paging: typing.Union['ObjsPaging', schemas.Unset] = schemas.unset,
        response_metadata: typing.Union['ObjsResponseMetadata', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FilesInfoResponse':
        return super().__new__(
            cls,
            *args,
            comments=comments,
            file=file,
            ok=ok,
            content_html=content_html,
            editor=editor,
            paging=paging,
            response_metadata=response_metadata,
            _configuration=_configuration,
            **kwargs,
        )

from slack_web_python_sdk.model.defs_ok_true import DefsOkTrue
from slack_web_python_sdk.model.defs_user_id import DefsUserId
from slack_web_python_sdk.model.objs_comments import ObjsComments
from slack_web_python_sdk.model.objs_file import ObjsFile
from slack_web_python_sdk.model.objs_paging import ObjsPaging
from slack_web_python_sdk.model.objs_response_metadata import ObjsResponseMetadata
