# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slack_web_python_sdk import schemas  # noqa: F401


class ObjsExternalOrgMigrations(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "current",
            "date_updated",
        }
        
        class properties:
        
            @staticmethod
            def current() -> typing.Type['ObjsExternalOrgMigrationsCurrent']:
                return ObjsExternalOrgMigrationsCurrent
            date_updated = schemas.IntSchema
            __annotations__ = {
                "current": current,
                "date_updated": date_updated,
            }
    
    current: 'ObjsExternalOrgMigrationsCurrent'
    date_updated: MetaOapg.properties.date_updated
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["current"]) -> 'ObjsExternalOrgMigrationsCurrent': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["date_updated"]) -> MetaOapg.properties.date_updated: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["current", "date_updated", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["current"]) -> 'ObjsExternalOrgMigrationsCurrent': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["date_updated"]) -> MetaOapg.properties.date_updated: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["current", "date_updated", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        current: 'ObjsExternalOrgMigrationsCurrent',
        date_updated: typing.Union[MetaOapg.properties.date_updated, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ObjsExternalOrgMigrations':
        return super().__new__(
            cls,
            *args,
            current=current,
            date_updated=date_updated,
            _configuration=_configuration,
            **kwargs,
        )

from slack_web_python_sdk.model.objs_external_org_migrations_current import ObjsExternalOrgMigrationsCurrent
