# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slack_web_python_sdk import schemas  # noqa: F401


class ObjsMessageIcons(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            emoji = schemas.StrSchema
            image_64 = schemas.StrSchema
            __annotations__ = {
                "emoji": emoji,
                "image_64": image_64,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["emoji"]) -> MetaOapg.properties.emoji: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["image_64"]) -> MetaOapg.properties.image_64: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["emoji", "image_64", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["emoji"]) -> typing.Union[MetaOapg.properties.emoji, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["image_64"]) -> typing.Union[MetaOapg.properties.image_64, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["emoji", "image_64", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        emoji: typing.Union[MetaOapg.properties.emoji, str, schemas.Unset] = schemas.unset,
        image_64: typing.Union[MetaOapg.properties.image_64, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ObjsMessageIcons':
        return super().__new__(
            cls,
            *args,
            emoji=emoji,
            image_64=image_64,
            _configuration=_configuration,
            **kwargs,
        )
