# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from slack_web_python_sdk import schemas  # noqa: F401


class UsersSetPhotoRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "token",
        }
        
        class properties:
            token = schemas.StrSchema
            crop_w = schemas.StrSchema
            crop_x = schemas.StrSchema
            crop_y = schemas.StrSchema
            image = schemas.StrSchema
            __annotations__ = {
                "token": token,
                "crop_w": crop_w,
                "crop_x": crop_x,
                "crop_y": crop_y,
                "image": image,
            }
    
    token: MetaOapg.properties.token
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["crop_w"]) -> MetaOapg.properties.crop_w: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["crop_x"]) -> MetaOapg.properties.crop_x: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["crop_y"]) -> MetaOapg.properties.crop_y: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["image"]) -> MetaOapg.properties.image: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["token", "crop_w", "crop_x", "crop_y", "image", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["token"]) -> MetaOapg.properties.token: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["crop_w"]) -> typing.Union[MetaOapg.properties.crop_w, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["crop_x"]) -> typing.Union[MetaOapg.properties.crop_x, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["crop_y"]) -> typing.Union[MetaOapg.properties.crop_y, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["image"]) -> typing.Union[MetaOapg.properties.image, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["token", "crop_w", "crop_x", "crop_y", "image", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        token: typing.Union[MetaOapg.properties.token, str, ],
        crop_w: typing.Union[MetaOapg.properties.crop_w, str, schemas.Unset] = schemas.unset,
        crop_x: typing.Union[MetaOapg.properties.crop_x, str, schemas.Unset] = schemas.unset,
        crop_y: typing.Union[MetaOapg.properties.crop_y, str, schemas.Unset] = schemas.unset,
        image: typing.Union[MetaOapg.properties.image, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UsersSetPhotoRequest':
        return super().__new__(
            cls,
            *args,
            token=token,
            crop_w=crop_w,
            crop_x=crop_x,
            crop_y=crop_y,
            image=image,
            _configuration=_configuration,
            **kwargs,
        )
