# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.admin_conversations_archive.post import ArchiveChannel
from slack_web_python_sdk.paths.admin_conversations_convert_to_private.post import ConvertToPrivateChannel
from slack_web_python_sdk.paths.admin_conversations_create.post import CreateChannelBasedConversation
from slack_web_python_sdk.paths.admin_conversations_delete.post import DeleteChannel
from slack_web_python_sdk.paths.admin_conversations_disconnect_shared.post import DisconnectSharedChannel
from slack_web_python_sdk.paths.admin_conversations_get_conversation_prefs.get import GetConversationPrefs
from slack_web_python_sdk.paths.admin_conversations_get_teams.get import GetTeamsList
from slack_web_python_sdk.paths.admin_conversations_invite.post import InviteUserToChannel
from slack_web_python_sdk.paths.admin_conversations_rename.post import RenameChannel
from slack_web_python_sdk.paths.admin_conversations_search.get import SearchChannels
from slack_web_python_sdk.paths.admin_conversations_set_conversation_prefs.post import SetConversationPrefs
from slack_web_python_sdk.paths.admin_conversations_set_teams.post import SetTeamsWorkspaceConnection
from slack_web_python_sdk.paths.admin_conversations_unarchive.post import UnarchiveChannel
from slack_web_python_sdk.apis.tags.admin_conversations_api_raw import AdminConversationsApiRaw


class AdminConversationsApi(
    ArchiveChannel,
    ConvertToPrivateChannel,
    CreateChannelBasedConversation,
    DeleteChannel,
    DisconnectSharedChannel,
    GetConversationPrefs,
    GetTeamsList,
    InviteUserToChannel,
    RenameChannel,
    SearchChannels,
    SetConversationPrefs,
    SetTeamsWorkspaceConnection,
    UnarchiveChannel,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AdminConversationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AdminConversationsApiRaw(api_client)
