# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.admin_invite_requests_denied_list.get import List
from slack_web_python_sdk.apis.tags.admin_invite_requests_denied_api_raw import AdminInviteRequestsDeniedApiRaw


class AdminInviteRequestsDeniedApi(
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AdminInviteRequestsDeniedApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AdminInviteRequestsDeniedApiRaw(api_client)
