# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.admin_emoji_add.post import AddEmoji
from slack_web_python_sdk.paths.admin_emoji_add_alias.post import AliasAdd
from slack_web_python_sdk.paths.admin_emoji_list.get import ListEnterpriseEmoji
from slack_web_python_sdk.paths.admin_emoji_remove.post import RemoveEnterpriseEmoji
from slack_web_python_sdk.paths.admin_emoji_rename.post import RenameEmoji
from slack_web_python_sdk.apis.tags.admin_emoji_api_raw import AdminEmojiApiRaw


class AdminEmojiApi(
    AddEmoji,
    AliasAdd,
    ListEnterpriseEmoji,
    RemoveEnterpriseEmoji,
    RenameEmoji,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AdminEmojiApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AdminEmojiApiRaw(api_client)
