# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.admin_teams_settings_info.get import GetInfo
from slack_web_python_sdk.paths.admin_teams_settings_set_default_channels.post import SetDefaultChannels
from slack_web_python_sdk.paths.admin_teams_settings_set_description.post import SetDescription
from slack_web_python_sdk.paths.admin_teams_settings_set_discoverability.post import SetDiscoverabilityOfWorkspace
from slack_web_python_sdk.paths.admin_teams_settings_set_icon.post import SetIcon
from slack_web_python_sdk.paths.admin_teams_settings_set_name.post import SetName
from slack_web_python_sdk.apis.tags.admin_teams_settings_api_raw import AdminTeamsSettingsApiRaw


class AdminTeamsSettingsApi(
    GetInfo,
    SetDefaultChannels,
    SetDescription,
    SetDiscoverabilityOfWorkspace,
    SetIcon,
    SetName,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: AdminTeamsSettingsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = AdminTeamsSettingsApiRaw(api_client)
