# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.calls_add.post import Add
from slack_web_python_sdk.paths.calls_participants_add.post import AddNewParticipant
from slack_web_python_sdk.paths.calls_end.post import End
from slack_web_python_sdk.paths.calls_info.get import Info
from slack_web_python_sdk.paths.calls_participants_remove.post import RegisterRemoved
from slack_web_python_sdk.paths.calls_update.post import Update
from slack_web_python_sdk.apis.tags.calls_api_raw import CallsApiRaw


class CallsApi(
    Add,
    AddNewParticipant,
    End,
    Info,
    RegisterRemoved,
    Update,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CallsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CallsApiRaw(api_client)
