# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.chat_scheduled_messages_list.get import List
from slack_web_python_sdk.apis.tags.chat_scheduled_messages_api_raw import ChatScheduledMessagesApiRaw


class ChatScheduledMessagesApi(
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ChatScheduledMessagesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ChatScheduledMessagesApiRaw(api_client)
