# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.conversations_archive.post import Archive
from slack_web_python_sdk.paths.conversations_close.post import Close
from slack_web_python_sdk.paths.conversations_create.post import Create
from slack_web_python_sdk.paths.conversations_history.get import History
from slack_web_python_sdk.paths.conversations_info.get import Info
from slack_web_python_sdk.paths.conversations_invite.post import Invite
from slack_web_python_sdk.paths.conversations_join.post import Join
from slack_web_python_sdk.paths.conversations_kick.post import Kick
from slack_web_python_sdk.paths.conversations_leave.post import Leave
from slack_web_python_sdk.paths.conversations_list.get import List
from slack_web_python_sdk.paths.conversations_mark.post import Mark
from slack_web_python_sdk.paths.conversations_members.get import Members
from slack_web_python_sdk.paths.conversations_open.post import Open
from slack_web_python_sdk.paths.conversations_rename.post import Rename
from slack_web_python_sdk.paths.conversations_replies.get import Replies
from slack_web_python_sdk.paths.conversations_set_purpose.post import SetPurpose
from slack_web_python_sdk.paths.conversations_set_topic.post import SetTopic
from slack_web_python_sdk.paths.conversations_unarchive.post import Unarchive
from slack_web_python_sdk.apis.tags.conversations_api_raw import ConversationsApiRaw


class ConversationsApi(
    Archive,
    Close,
    Create,
    History,
    Info,
    Invite,
    Join,
    Kick,
    Leave,
    List,
    Mark,
    Members,
    Open,
    Rename,
    Replies,
    SetPurpose,
    SetTopic,
    Unarchive,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ConversationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ConversationsApiRaw(api_client)
