# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.dnd_end_dnd.post import EndDndRaw
from slack_web_python_sdk.paths.dnd_end_snooze.post import EndSnoozeRaw
from slack_web_python_sdk.paths.dnd_info.get import InfoRaw
from slack_web_python_sdk.paths.dnd_set_snooze.post import SetSnoozeRaw
from slack_web_python_sdk.paths.dnd_team_info.get import TeamInfoRaw


class DndApiRaw(
    EndDndRaw,
    EndSnoozeRaw,
    InfoRaw,
    SetSnoozeRaw,
    TeamInfoRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
