# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.files_remote_add.post import AddFromRemote
from slack_web_python_sdk.paths.files_delete.post import Delete
from slack_web_python_sdk.paths.files_comments_delete.post import DeleteComment
from slack_web_python_sdk.paths.files_remote_remove.post import DeleteFile
from slack_web_python_sdk.paths.files_remote_info.get import GetInfo
from slack_web_python_sdk.paths.files_info.get import Info
from slack_web_python_sdk.paths.files_list.get import List
from slack_web_python_sdk.paths.files_remote_list.get import ListRemoteFiles
from slack_web_python_sdk.paths.files_revoke_public_url.post import RevokePublicUrl
from slack_web_python_sdk.paths.files_remote_share.get import ShareRemoteFile
from slack_web_python_sdk.paths.files_shared_public_url.post import SharedPublicUrl
from slack_web_python_sdk.paths.files_remote_update.post import UpdateRemoteFile
from slack_web_python_sdk.paths.files_upload.post import Upload
from slack_web_python_sdk.apis.tags.files_api_raw import FilesApiRaw


class FilesApi(
    AddFromRemote,
    Delete,
    DeleteComment,
    DeleteFile,
    GetInfo,
    Info,
    List,
    ListRemoteFiles,
    RevokePublicUrl,
    ShareRemoteFile,
    SharedPublicUrl,
    UpdateRemoteFile,
    Upload,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FilesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FilesApiRaw(api_client)
