# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.files_remote_add.post import AddFromRemoteRaw
from slack_web_python_sdk.paths.files_remote_remove.post import DeleteFileRaw
from slack_web_python_sdk.paths.files_remote_info.get import GetInfoRaw
from slack_web_python_sdk.paths.files_remote_list.get import ListRemoteFilesRaw
from slack_web_python_sdk.paths.files_remote_share.get import ShareRemoteFileRaw
from slack_web_python_sdk.paths.files_remote_update.post import UpdateRemoteFileRaw


class FilesRemoteApiRaw(
    AddFromRemoteRaw,
    DeleteFileRaw,
    GetInfoRaw,
    ListRemoteFilesRaw,
    ShareRemoteFileRaw,
    UpdateRemoteFileRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
