# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.files_remote_add.post import AddFromRemote
from slack_web_python_sdk.paths.files_remote_remove.post import DeleteFile
from slack_web_python_sdk.paths.files_remote_info.get import GetInfo
from slack_web_python_sdk.paths.files_remote_list.get import ListRemoteFiles
from slack_web_python_sdk.paths.files_remote_share.get import ShareRemoteFile
from slack_web_python_sdk.paths.files_remote_update.post import UpdateRemoteFile
from slack_web_python_sdk.apis.tags.files_remote_api_raw import FilesRemoteApiRaw


class FilesRemoteApi(
    AddFromRemote,
    DeleteFile,
    GetInfo,
    ListRemoteFiles,
    ShareRemoteFile,
    UpdateRemoteFile,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FilesRemoteApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FilesRemoteApiRaw(api_client)
