# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.oauth_access.get import Access
from slack_web_python_sdk.paths.oauth_v2_access.get import ExchangeToken
from slack_web_python_sdk.paths.oauth_token.get import Token
from slack_web_python_sdk.apis.tags.oauth_api_raw import OauthApiRaw


class OauthApi(
    Access,
    ExchangeToken,
    Token,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OauthApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OauthApiRaw(api_client)
