# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.reminders_add.post import Add
from slack_web_python_sdk.paths.reminders_complete.post import Complete
from slack_web_python_sdk.paths.reminders_delete.post import Delete
from slack_web_python_sdk.paths.reminders_info.get import Info
from slack_web_python_sdk.paths.reminders_list.get import List
from slack_web_python_sdk.apis.tags.reminders_api_raw import RemindersApiRaw


class RemindersApi(
    Add,
    Complete,
    Delete,
    Info,
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RemindersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RemindersApiRaw(api_client)
