# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.usergroups_create.post import Create
from slack_web_python_sdk.paths.usergroups_disable.post import Disable
from slack_web_python_sdk.paths.usergroups_enable.post import Enable
from slack_web_python_sdk.paths.usergroups_list.get import List
from slack_web_python_sdk.paths.usergroups_users_list.get import ListAllUsers
from slack_web_python_sdk.paths.usergroups_update.post import Update
from slack_web_python_sdk.paths.usergroups_users_update.post import UpdateList
from slack_web_python_sdk.apis.tags.usergroups_api_raw import UsergroupsApiRaw


class UsergroupsApi(
    Create,
    Disable,
    Enable,
    List,
    ListAllUsers,
    Update,
    UpdateList,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsergroupsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsergroupsApiRaw(api_client)
