# coding: utf-8

"""
    Slack Web API

    One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.

    The version of the OpenAPI document: 1.7.0
    Created by: https://api.slack.com/support
"""

from slack_web_python_sdk.paths.views_open.get import OpenRaw
from slack_web_python_sdk.paths.views_publish.get import PublishRaw
from slack_web_python_sdk.paths.views_push.get import PushRaw
from slack_web_python_sdk.paths.views_update.get import UpdateRaw


class ViewsApiRaw(
    OpenRaw,
    PublishRaw,
    PushRaw,
    UpdateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
